#!/usr/bin/bash 

export                TFM_SETTINGS=$TFM_DIR/examples/settings_example
export TFM_KNOWN_BOARDREADERS_LIST=$TFM_DIR/examples/known_boardreaders_list_example
export         TFM_FHICL_DIRECTORY=$TFM_DIR/config

if [[ "$TFM_FHICL_DIRECTORY" == "IGNORED" ]]; then
    echo "Put code here which sets up the database environment"
fi

if [ -z $TFM_LOGDIR ] ; then export TFM_LOGDIR=/tmp/daqinterface_$USER ; fi

export TFM_USER_SOURCEFILE_ERRNO=0
export      TFM_PARTITION_NUMBER=0

return 0
