#!/usr/bin/bash 

export                TFM_TEST_DIR=$PWD/tfm_test
if [ ! -d $TFM_TEST_DIR ] ; then mkdir -p $TFM_TEST_DIR ; fi

export                TFM_SETTINGS=$TFM_TEST_DIR/settings
export TFM_KNOWN_BOARDREADERS_LIST=$TFM_TEST_DIR/known_boardreaders_list
export         TFM_FHICL_DIRECTORY=$TFM_DIR/config
export                  TFM_LOGDIR=$TFM_TEST_DIR/Logs/tfm

if [[ "$TFM_FHICL_DIRECTORY" == "IGNORED" ]]; then
    echo "Put code here which sets up the database environment"
fi

export TFM_USER_SOURCE_ME_ERRNO=0
export  ARTDAQ_PARTITION_NUMBER=8

return 0
